package com.aidatabaseassistant.audit.enums;

public enum AuditEventType {
    LOGIN,
    LOGOUT,
    REGISTER,
    PROFILE_UPDATED,
    PASSWORD_CHANGED,
    CONNECTION_CREATED,
    CONNECTION_UPDATED,
    CONNECTION_DELETED,
    CONNECTION_TESTED,
    CHAT_CREATED,
    CHAT_RENAMED,
    CHAT_DELETED,
    QUERY_EXECUTED,
    QUERY_FAILED,
    AI_PROVIDER_USED,
    AI_PROVIDER_FALLBACK,
    POLICY_VIOLATION,
    UNAUTHORIZED_ACCESS,
    INVALID_JWT,
    CSV_EXPORT,
    PDF_EXPORT
}
