package com.aidatabaseassistant.validation;

import net.sf.jsqlparser.JSQLParserException;
import net.sf.jsqlparser.parser.CCJSqlParserUtil;
import net.sf.jsqlparser.statement.Statement;
import net.sf.jsqlparser.statement.Statements;
import net.sf.jsqlparser.statement.select.Select;
import org.springframework.stereotype.Component;

@Component
public class SqlValidator {

    /**
     * Parses the raw SQL string and ensures it is a single, valid SELECT statement.
     * @param rawSql The raw SQL generated by the AI
     * @return The parsed Select statement object if validation passes
     * @throws SqlValidationException if parsing fails, if there are multiple statements, or if it is not a SELECT
     */
    public Select validateAndParse(String rawSql) {
        if (rawSql == null || rawSql.trim().isEmpty()) {
            throw new SqlValidationException("Generated SQL is empty.");
        }

        try {
            // Use Statements to check if multiple statements were provided (e.g. "SELECT *; DROP TABLE;")
            Statements statements = CCJSqlParserUtil.parseStatements(rawSql);
            if (statements.size() > 1) {
                throw new SqlValidationException("Multiple SQL statements detected. Only a single statement is allowed.");
            }

            Statement statement = statements.get(0);
            
            // Strictly require a SELECT statement (blocks INSERT, UPDATE, DELETE, DROP, etc.)
            if (!(statement instanceof Select)) {
                throw new SqlValidationException("Forbidden statement type: " + statement.getClass().getSimpleName() + ". Only SELECT statements are permitted.");
            }

            return (Select) statement;

        } catch (JSQLParserException e) {
            throw new SqlValidationException("SQL syntax is invalid and could not be parsed: " + e.getMessage());
        }
    }
}
