package com.aidatabaseassistant.audit.model;

public enum EventType {
    LOGIN,
    LOGOUT,
    REGISTRATION,
    PASSWORD_CHANGED,
    PROFILE_UPDATED,
    CONNECTION_CREATED,
    CONNECTION_UPDATED,
    CONNECTION_DELETED,
    CONNECTION_TESTED,
    PROMPT_SENT,
    PROVIDER_USED,
    PROVIDER_SWITCHED,
    AI_TIMEOUT,
    QUERY_EXECUTED,
    QUERY_FAILED,
    CSV_EXPORT,
    PDF_EXPORT,
    SQL_INJECTION_BLOCKED,
    POLICY_VIOLATION,
    UNAUTHORIZED_REQUEST,
    INVALID_JWT,
    CHAT_CREATED,
    CHAT_DELETED,
    CHAT_RENAMED
}
